<?php

use function App\Shared\Helpers\the_published_date;
use function App\Shared\Helpers\the_title;
use function Qubus\Security\Helpers\t__;
use function Qubus\Support\Helpers\truncate_string;

$this->parent('theme::Vapor/views/layout');
$this->block('vapor-content', function ($param) {
    ?>

    <?php foreach ($param['content'] as $p): ?>
        <article class="preview">
            <header>
                <h2 class="post-title"><a href="<?=$p['slug'];?>"><?=the_title($p['id']);?></a></h2>
                <div class="post-meta"><time><?=the_published_date($p['id']);?></time></div>
            </header>
            <?php if (!empty($p['featuredImage'])) { ?>
                <div class="featured featured-image">
                    <a href="<?=$p['slug'];?>"><img itemprop="image" width="100%" src="<?=$p['featuredImage'];?>" alt="<?=the_title($p['id']);?>"/></a>
                </div>
            <?php } ?>
            <section class="post-excerpt">
                <?=truncate_string(string: $p['body'], limit: 250, isHtml: true); ?>
                <p class="readmore"><a href="<?=$p['slug'];?>"><?=t__(msgid: 'read more . . .', domain: 'vapor-theme'); ?> <i class="fa fa-chevron-circle-right"></i></a></p>
            </section>
        </article>
    <?php endforeach;?>
    <?php if ($param['paginator']->getNumPages() > 1): ?>
        <nav class="pagination" role="pagination">
            <?php if ($param['paginator']->getPrevUrl()): ?>
                <a class="newer-posts" href="<?=$param['paginator']->getPrevUrl();?>"><i class="fa fa-chevron-circle-left"></i> <?=t__(msgid: 'Newer', domain: 'vapor-theme');?></a>
            <?php endif; ?>
            <?php if ($param['paginator']->getNextUrl()): ?>
                <a class="older-posts" href="<?=$param['paginator']->getNextUrl();?>"><?=t__(msgid: 'Older', domain: 'vapor-theme');?> <i class="fa fa-chevron-circle-right"></i></a>
            <?php endif; ?>
        </nav>
    <?php endif; ?>

<?php }); ?>