<?php
use App\Shared\Services\Registry as r;
use App\Infrastructure\Services\Options;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\cms_footer;
use function App\Shared\Helpers\cms_head;
use function App\Shared\Helpers\image_directory_uri;
use function App\Shared\Helpers\site_url;
use function Qubus\Security\Helpers\t__;

$option = Options::factory();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title><?=$title;?></title>
    <meta name="description" content="<?=$option->read(optionKey: 'site_description');?>"/>
    <?php cms_head(); ?>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?subset=latin,cyrillic-ext,latin-ext,cyrillic&family=Open+Sans+Condensed:300|Open+Sans:400,600,400italic,600italic|Merriweather:400,300,300italic,400italic,700,700italic|Roboto+Slab:400,300">
</head>
<body class="home-template">
<header id="site-head">
    <a id="blog-logo" href="<?=site_url();?>"><div class="bloglogo" style="background: url(<?=image_directory_uri();?>avatar.png)"></div></a>
    <?php if(!$single) {?>
        <h1 class="blog-title"><a href="<?=site_url();?>"><?=$option->read(optionKey: 'sitename');?></a></h1>
    <?php } else { ?>
        <h2 class="blog-title"><a href="<?=site_url();?>"><?=$option->read(optionKey: 'sitename');?></a></h2>
    <?php } ?>
    <nav class="menu" role="nav">
        <?php Action::getInstance()->doAction('vapor_theme_menu'); ?>
    </nav>
</header>
<main class="content" role="main">
    <?php $this->block('vapor-content'); ?>
</main>
<footer class="site-footer">
    <div class="inner">
        <section class="footer-description"><?=$option->read(optionKey: 'site_description');?></section>
        <section class="copyright">&copy; <?=date(format: 'Y');?>. <?=t__(msgid: 'All rights reserved.', domain: r::getInstance()->get('vapor-theme')['id']);?></section>
        <section><?=t__(msgid: 'Design by', domain: r::getInstance()->get('vapor-theme')['id']);?> <a target="_blank" href="//sethlilly.com/" rel="nofollow">Seth Lilly</a></section>
    </div>
</footer>
<?php cms_footer(); ?>
</body>
</html>